import React from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "/styles/Task/AllTask.module.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faEnvelope, faUser, faMagnifyingGlass, faBoxArchive } from "@fortawesome/free-solid-svg-icons";
import { faFileLines } from "@fortawesome/free-regular-svg-icons";

export default function CompanyAssets() {
  return (
    <div className={styles.body}>
      <Head>
        <title>Company Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous"></link>
      </Head>

      <main className={styles.main} id="main">
        <nav className={styles.navbar}>
          <ul className={styles.navList}>
            <li className={styles.navItem}>
              <Image className={styles.imageLogo} src="/EasyHandler_Hitam.png" alt="logo" width={42} height={42} />
            </li>
            <li className={styles.navItem}>
              <FontAwesomeIcon className={`${styles.navIcon}`} icon={faEnvelope} />
            </li>
            <li className={styles.navItem}>
              <FontAwesomeIcon className={`${styles.navIcon}`} icon={faUser} />
            </li>
          </ul>
        </nav>

        <main className={`${styles.body} mt-4`}>
          <div class="d-flex justify-content-between">
            <div class="ms-4">
              <div class="header mb-4">
                <h4>Tasks</h4>
              </div>
              <section className={`${styles.text}`}>
                <Link href="#">
                  <div className={`mb-2`}>
                    <a className={styles.textA}>
                      <FontAwesomeIcon icon={faFileLines} className={styles.icon} /> <span>All Task</span>
                    </a>
                  </div>
                </Link>

                <Link href="#">
                  <div>
                    <a className={styles.textA2}>
                      <FontAwesomeIcon icon={faBoxArchive} className={styles.icon} /> <span>Projects</span>
                    </a>
                  </div>
                </Link>
              </section>
            </div>

            <div class={`${styles.vl}`} />

            <section className={`${styles.select} section-sellect-search w-75`}>
              <div class="container-fluid">
                <div>
                  <h5>Company</h5>
                  <h2 class="mb-5">All tasks</h2>
                </div>
                <div className={`${styles.formSelect} row`}>
                  <div class="col-3">
                    <select className={`form-select`} id="select">
                      <option>All assignee</option>
                      <option value="25">Viona Pasha</option>
                      <option value="50">Mahmud derawan</option>
                      <option value="75">Linda Maria</option>
                      <option value="100">Nurul</option>
                    </select>
                  </div>

                  <div class="col-3">
                    <select className={`form-select`} id="select">
                      <option selected>All project</option>
                      {/* <option value="25">25</option>
                      <option value="50">50</option>
                      <option value="75">75</option>
                      <option value="100">100</option> */}
                    </select>
                  </div>
                </div>
              </div>
            </section>
          </div>
          <section class="section-sellect-search">
            <div class="container-fluid">
              <div class="row mt-3 justify-content-end me-1">
                <div class="col-3">
                  <div className={`input-group mb-3`}>
                    <span className={`${styles.spanIcon} input-group-text`}>
                      <FontAwesomeIcon className={styles.searchIcon} icon={faMagnifyingGlass} />
                    </span>
                    <input type="text" className={`${styles.searchInput} form-control`} placeholder="search task by name"></input>
                  </div>
                </div>
              </div>
            </div>
          </section>

        </main>

        <div className={`${styles.image} mt-2`}>
          <img src="/image_580.png"></img>
          <h4>No task to do</h4>
          <p>All task to do will show up here.</p>
          <button type="button" className={`${styles.button} btn btn-primary`}>
            Create new task
          </button>
        </div>
      </main>

      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    </div>
  );
}
